#!/usr/bin/env bash
# Tests for bin/nm-pr-format: the no-mistakes PR-body reformatter, tracked
# fleet-wide (ticket 4/5 of the PR-format workstream; see the script's own
# docstring for the full contract).
#
# Matrix:
#   (a) --evidence adds a '## Evidence' section between '## How' and '## Testing'
#   (b) omitting --evidence is byte-identical to the pre-ticket-4 output shape
#   (c) --how still lands in '## How' unchanged (regression)
#   (d) double --apply on the same checks-green event is idempotent: the second
#       call exits EXIT_ALREADY_REFORMATTED (3) and leaves the PR body untouched
#   (e) a genuine gh failure exits EXIT_ERROR (1), distinct from (d)
#   (f) --force bypasses the already-reformatted guard (regression)
set -u

# shellcheck source=tests/lib.sh disable=SC1091
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

SCRIPT="$ROOT/bin/nm-pr-format"
TMP_ROOT=$(fm_test_tmproot nm-pr-format-tests)

EXIT_ERROR=1
EXIT_ALREADY_REFORMATTED=3

# A raw no-mistakes-shaped body: Risk Assessment / What Changed / Testing /
# Pipeline (with a **Test** step) / a cubic footer — matches the compiled
# shape the script's docstring describes.
RAW_BODY='## Risk Assessment

Low risk.

## What Changed

- <code>Added foo</code>
- <code>Fixed bar</code>

## Testing

Ran the suite locally before pushing.

<details><summary>Evidence</summary>

some evidence blob

</details>

## Pipeline

<details><summary>**Test**</summary>

- Ran unit tests
- Ran e2e tests
</details>

Generated by no-mistakes.'

# make_case <name>: fresh sandbox with a fakebin dir and a body-state file
# seeded with RAW_BODY. Echoes the case dir.
make_case() {
  local name=$1 case_dir
  case_dir="$TMP_ROOT/$name"
  mkdir -p "$case_dir/fakebin"
  printf '%s\n' "$RAW_BODY" > "$case_dir/body.txt"
  printf '%s\n' "$case_dir"
}

# add_gh_mock <case_dir>: a `gh` stub backing `pr view`/`pr edit` with a
# mutable body file, so `--apply` really changes what the next `pr view` sees.
add_gh_mock() {
  local case_dir=$1
  cat > "$case_dir/fakebin/gh" <<SH
#!/usr/bin/env bash
BODY_FILE="$case_dir/body.txt"
case "\${1:-} \${2:-}" in
  "pr view")
    body=\$(cat "\$BODY_FILE")
    python3 -c "import json,sys; print(json.dumps({'number':9,'title':'API-1234: test change','body': sys.argv[1]}))" "\$body"
    exit 0
    ;;
  "pr edit")
    prev=""
    for a in "\$@"; do
      if [ "\$prev" = "--body-file" ]; then cp "\$a" "\$BODY_FILE"; fi
      prev="\$a"
    done
    exit 0
    ;;
esac
exit 0
SH
  chmod +x "$case_dir/fakebin/gh"
}

# add_gh_mock_view_fails <case_dir> <message>: a `gh` stub whose `pr view`
# always fails, simulating a genuine error (auth failure, PR not found, ...).
add_gh_mock_view_fails() {
  local case_dir=$1 message=$2
  cat > "$case_dir/fakebin/gh" <<SH
#!/usr/bin/env bash
case "\${1:-} \${2:-}" in
  "pr view") echo "$message" >&2; exit 1 ;;
esac
exit 0
SH
  chmod +x "$case_dir/fakebin/gh"
}

run_fmt() {
  local case_dir=$1; shift
  PATH="$case_dir/fakebin:$PATH" "$SCRIPT" "$@"
}

test_evidence_positioned_between_how_and_testing() {
  local case_dir out
  case_dir=$(make_case evidence-position)
  add_gh_mock "$case_dir"

  out=$(run_fmt "$case_dir" 9 --how '```mermaid
graph TD; A-->B;
```' --evidence '![shot](https://example.invalid/shot.png)' 2>/dev/null)

  assert_contains "$out" $'## How\n\n```mermaid' "evidence-position: How section missing or malformed"
  assert_contains "$out" $'## Evidence\n\n![shot](https://example.invalid/shot.png)' \
    "evidence-position: Evidence section missing or malformed"

  local how_idx evidence_idx testing_idx
  how_idx=$(printf '%s' "$out" | grep -n '^## How$' | head -1 | cut -d: -f1)
  evidence_idx=$(printf '%s' "$out" | grep -n '^## Evidence$' | head -1 | cut -d: -f1)
  testing_idx=$(printf '%s' "$out" | grep -n '^## Testing$' | head -1 | cut -d: -f1)
  [ -n "$how_idx" ] && [ -n "$evidence_idx" ] && [ -n "$testing_idx" ] \
    || fail "evidence-position: could not locate all three section headers"
  [ "$how_idx" -lt "$evidence_idx" ] || fail "evidence-position: Evidence did not come after How"
  [ "$evidence_idx" -lt "$testing_idx" ] || fail "evidence-position: Evidence did not come before Testing"
  pass "nm-pr-format positions Evidence after How and before Testing"
}

test_evidence_omitted_before_after_byte_identical() {
  local case_dir before after
  case_dir=$(make_case evidence-omitted)
  add_gh_mock "$case_dir"

  before=$(run_fmt "$case_dir" 9 2>/dev/null)
  after=$(run_fmt "$case_dir" 9 2>/dev/null)
  [ "$before" = "$after" ] || fail "evidence-omitted: repeated dry runs of the same body diverged"
  assert_not_contains "$before" "## Evidence" \
    "evidence-omitted: an Evidence section appeared without --evidence being passed"
  pass "nm-pr-format omits --evidence produces no Evidence section"
}

test_how_unchanged_regression() {
  local case_dir out
  case_dir=$(make_case how-regression)
  add_gh_mock "$case_dir"

  out=$(run_fmt "$case_dir" 9 --how 'Explains the approach.' 2>/dev/null)
  assert_contains "$out" $'## How\n\nExplains the approach.' \
    "how-regression: --how content did not land in ## How unchanged"
  pass "nm-pr-format --how still lands in ## How unchanged"
}

test_double_apply_is_idempotent() {
  local case_dir rc1 rc2 body_after_first body_after_second stderr2
  case_dir=$(make_case double-apply)
  add_gh_mock "$case_dir"

  set +e
  run_fmt "$case_dir" 9 --apply > "$case_dir/out1" 2> "$case_dir/err1"
  rc1=$?
  set -e
  expect_code 0 "$rc1" "double-apply: first --apply should succeed"
  body_after_first=$(cat "$case_dir/body.txt")
  assert_not_contains "$body_after_first" "## Pipeline" \
    "double-apply: first apply should have dropped the raw Pipeline section"

  set +e
  run_fmt "$case_dir" 9 --apply > "$case_dir/out2" 2> "$case_dir/err2"
  rc2=$?
  set -e
  expect_code "$EXIT_ALREADY_REFORMATTED" "$rc2" \
    "double-apply: second --apply on the same checks-green event should hit the already-reformatted skip"

  body_after_second=$(cat "$case_dir/body.txt")
  [ "$body_after_first" = "$body_after_second" ] \
    || fail "double-apply: second --apply mutated an already-reformatted body"

  stderr2=$(cat "$case_dir/err2")
  assert_contains "$stderr2" "already reformatted" \
    "double-apply: skip message missing from stderr"
  pass "nm-pr-format is idempotent across two --apply calls for the same checks-green event"
}

test_genuine_error_has_distinct_exit_code() {
  local case_dir rc err
  case_dir=$(make_case genuine-error)
  add_gh_mock_view_fails "$case_dir" "gh: authentication failed"

  set +e
  run_fmt "$case_dir" 9 --apply > "$case_dir/out" 2> "$case_dir/err"
  rc=$?
  set -e

  expect_code "$EXIT_ERROR" "$rc" "genuine-error: a real gh failure should exit $EXIT_ERROR"
  err=$(cat "$case_dir/err")
  assert_contains "$err" "gh error" "genuine-error: stderr did not report the gh failure"
  [ "$rc" != "$EXIT_ALREADY_REFORMATTED" ] \
    || fail "genuine-error: real error must not share the already-reformatted exit code"
  pass "nm-pr-format distinguishes a genuine gh error from the already-reformatted skip via exit code"
}

test_force_bypasses_guard_regression() {
  local case_dir rc
  case_dir=$(make_case force-bypass)
  add_gh_mock "$case_dir"

  run_fmt "$case_dir" 9 --apply > /dev/null 2>&1 || fail "force-bypass: first apply failed"

  set +e
  run_fmt "$case_dir" 9 --apply --force > "$case_dir/out" 2> "$case_dir/err"
  rc=$?
  set -e
  expect_code 0 "$rc" "force-bypass: --force should override the already-reformatted guard"
  pass "nm-pr-format --force still bypasses the already-reformatted guard"
}

test_testing_bullet_leading_dashes_preserved() {
  local case_dir out
  case_dir=$(make_case testing-bullet-dashes)
  add_gh_mock "$case_dir"

  out=$(run_fmt "$case_dir" 9 --testing $'- -- flag names unaffected\n- ** bold marker unaffected' 2>/dev/null)
  assert_contains "$out" $'- -- flag names unaffected' \
    "testing-bullet-dashes: a bullet's own leading '--' was over-stripped"
  assert_contains "$out" $'- ** bold marker unaffected' \
    "testing-bullet-dashes: a bullet's own leading '**' was over-stripped"
  pass "nm-pr-format --testing strips only the bullet marker, not the bullet's own leading dashes/asterisks"
}

test_evidence_positioned_between_how_and_testing
test_evidence_omitted_before_after_byte_identical
test_how_unchanged_regression
test_double_apply_is_idempotent
test_genuine_error_has_distinct_exit_code
test_force_bypasses_guard_regression
test_testing_bullet_leading_dashes_preserved
